//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveGoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int Id { get; set; }
        public System.DateTime MoveDT { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Capacity { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
